apiVersion: apps/v1
kind: Deployment
metadata:
  # Deploymentの名前. Namespace内ではユニークである必要がある.
  name: client-deployment
spec:
  # レプリカ数の指定
  replicas: 1
  selector:
    matchLabels:
      component: web
  # Podのテンプレート(PodTemplate)
  template:
    metadata:
      labels:
        # ラベル指定は必須
        component: web
    spec:
      containers:
        - name: client
          image: solareenlo/multi-client
          ports:
            - containerPort: 3000
